# .readthedocs.yaml

version: 1



build:
  os: ubuntu-20.04
  tools:
    python: "3.10"  # Specify the Python version used in the project
  # jobs: 2  # Number of parallel build jobs

python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt  # Install project dependencies
    - method: pip
      packages:
        - sphinx
        - sphinx-rtd-theme
        - torch  # Include PyTorch
        - torchvision
        - matplotlib
        - pandas
        - scikit-learn
        - pillow

sphinx:
  configuration: docs/conf.py  # Path to the Sphinx configuration file

# Explicit environment variables (optional, set if required by the project)
environment:
  # Example: Set this if your project needs a specific model directory or data root
  # - name: MODEL_DIR
  #   value: "/path/to/model"
  - name: DATA_DIR
    value: "data"

# formats:
#   - html
#   - pdf

# Optional: Add extra steps like generating plots or preprocessing during documentation build
build:
  steps:
    - echo "Running pre-build steps..."
    - python scripts/preprocess.py  # Example: Run a preprocessing script
